version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: optimizer
      POSTGRES_PASSWORD: optimizer_pass
      POSTGRES_DB: optimizer_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: ./backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:
